name: Maven Build & Docker Push

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, windows, docker-desktop]
    # runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Verify Java & Maven
      - name: Verify Java & Maven
        run: |
          java -version
          mvn -version

      # # Setup Java
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: temurin
      #     java-version: 17
      #     cache: maven

      # Maven build
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Login to Docker Hub (ONLY for master branch)
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-maven:0.1.0 .

      # Push Docker image (ONLY for master branch)
      - name: Push Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-maven:0.1.0
